### PR TITLE
Mock up example directory structure

### PR DESCRIPTION
**Pull request by johnctitus**
Initial directory format.

### CODE REVIEW

**Review by cnethers — DISMISSED** [review]

**Review by cnethers — DISMISSED** [review]
LGTM

**Review by halfshellhero — COMMENTED** [review]
Could we get a sync of the example number references to the actual wiki page?  the TOC in wiki doesn't have many of the sections noted here (IE 4.2.4, 4.2.5, and 4.3.2.6 doesn't exist in the wiki TOC)

**Comment by johnctitus** [comment]
Wiki & directory layout updated and synced.

**Review by cnethers — APPROVED** [review]
LGTM

**Review by halfshellhero — APPROVED** [review]
thanks for the remap!

**Pull request merged**
